import "server-only";

import { AsyncLocalStorage } from "node:async_hooks";
import fs from "node:fs";
import path from "node:path";
import { DatabaseSync } from "node:sqlite";
import postgres from "postgres";

type RunResult = { changes: number; lastInsertRowid: number | bigint };

type Statement = {
  get(...params: unknown[]): Promise<unknown>;
  all(...params: unknown[]): Promise<unknown[]>;
  run(...params: unknown[]): Promise<RunResult>;
};

type Db = {
  prepare(sql: string): Statement;
  exec(sql: string): Promise<void>;
};

type QueryClient = {
  unsafe(
    query: string,
    parameters?: Array<string | number | boolean | null>,
  ): Promise<Array<Record<string, unknown>> & { count: number }>;
  reserve(): Promise<QueryClient & { release(): void }>;
};

type SessionState = {
  holding: boolean;
  reserved: (QueryClient & { release(): void }) | null;
};

const sessions = new AsyncLocalStorage<SessionState>();

function session(): SessionState {
  const current = sessions.getStore();
  if (current) return current;
  const created: SessionState = { holding: false, reserved: null };
  sessions.enterWith(created);
  return created;
}

const SQLITE_SCHEMA = `
    CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT,
      email_verified INTEGER NOT NULL DEFAULT 0,
      verification_token TEXT,
      verification_expires INTEGER,
      reset_token TEXT,
      reset_expires INTEGER,
      created_at INTEGER NOT NULL,
      updated_at INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS oauth_accounts (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      provider TEXT NOT NULL,
      provider_account_id TEXT NOT NULL,
      created_at INTEGER NOT NULL,
      UNIQUE(provider, provider_account_id)
    );

    CREATE TABLE IF NOT EXISTS preferences (
      user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      episode_alerts INTEGER NOT NULL DEFAULT 1,
      product_news INTEGER NOT NULL DEFAULT 0,
      security_email INTEGER NOT NULL DEFAULT 1
    );

    CREATE TABLE IF NOT EXISTS progress (
      user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      series_id TEXT NOT NULL,
      highest_opened INTEGER NOT NULL DEFAULT 0,
      updated_at INTEGER NOT NULL,
      PRIMARY KEY (user_id, series_id)
    );

    CREATE TABLE IF NOT EXISTS messages (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL,
      body TEXT NOT NULL,
      created_at INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS suggestions (
      id TEXT PRIMARY KEY,
      idea TEXT NOT NULL,
      email TEXT,
      created_at INTEGER NOT NULL
    );

    CREATE TABLE IF NOT EXISTS dev_links (
      id INTEGER PRIMARY KEY AUTOINCREMENT,
      user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
      email TEXT NOT NULL,
      kind TEXT NOT NULL,
      url TEXT NOT NULL,
      created_at INTEGER NOT NULL
    );

    CREATE INDEX IF NOT EXISTS idx_users_verification ON users(verification_token);
    CREATE INDEX IF NOT EXISTS idx_users_reset ON users(reset_token);
  `;

// Postgres INTEGER is 32-bit. Timestamps are stored as milliseconds, so those columns are BIGINT.
const POSTGRES_SCHEMA = [
  `CREATE TABLE IF NOT EXISTS users (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL UNIQUE,
      password_hash TEXT,
      email_verified INTEGER NOT NULL DEFAULT 0,
      verification_token TEXT,
      verification_expires BIGINT,
      reset_token TEXT,
      reset_expires BIGINT,
      created_at BIGINT NOT NULL,
      updated_at BIGINT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS oauth_accounts (
      id TEXT PRIMARY KEY,
      user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      provider TEXT NOT NULL,
      provider_account_id TEXT NOT NULL,
      created_at BIGINT NOT NULL,
      UNIQUE(provider, provider_account_id)
    )`,
  `CREATE TABLE IF NOT EXISTS preferences (
      user_id TEXT PRIMARY KEY REFERENCES users(id) ON DELETE CASCADE,
      episode_alerts INTEGER NOT NULL DEFAULT 1,
      product_news INTEGER NOT NULL DEFAULT 0,
      security_email INTEGER NOT NULL DEFAULT 1
    )`,
  `CREATE TABLE IF NOT EXISTS progress (
      user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
      series_id TEXT NOT NULL,
      highest_opened INTEGER NOT NULL DEFAULT 0,
      updated_at BIGINT NOT NULL,
      PRIMARY KEY (user_id, series_id)
    )`,
  `CREATE TABLE IF NOT EXISTS messages (
      id TEXT PRIMARY KEY,
      name TEXT NOT NULL,
      email TEXT NOT NULL,
      body TEXT NOT NULL,
      created_at BIGINT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS suggestions (
      id TEXT PRIMARY KEY,
      idea TEXT NOT NULL,
      email TEXT,
      created_at BIGINT NOT NULL
    )`,
  `CREATE TABLE IF NOT EXISTS dev_links (
      id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id TEXT REFERENCES users(id) ON DELETE CASCADE,
      email TEXT NOT NULL,
      kind TEXT NOT NULL,
      url TEXT NOT NULL,
      created_at BIGINT NOT NULL
    )`,
  `CREATE INDEX IF NOT EXISTS idx_users_verification ON users(verification_token)`,
  `CREATE INDEX IF NOT EXISTS idx_users_reset ON users(reset_token)`,
];

class Mutex {
  private locked = false;
  private waiters: Array<() => void> = [];

  lock(): Promise<void> {
    if (!this.locked) {
      this.locked = true;
      return Promise.resolve();
    }
    return new Promise((resolve) => {
      this.waiters.push(resolve);
    });
  }

  unlock(): void {
    const next = this.waiters.shift();
    if (next) next();
    else this.locked = false;
  }
}

function createSqlite(): Db {
  const dir = path.join(process.cwd(), "data");
  fs.mkdirSync(dir, { recursive: true });
  const database = new DatabaseSync(path.join(dir, "dramame.db"));
  database.exec("PRAGMA journal_mode = WAL");
  database.exec("PRAGMA foreign_keys = ON");

  const mutex = new Mutex();
  let schemaReady = false;
  let txOpen = false;

  const ensure = () => {
    if (schemaReady) return;
    database.exec(SQLITE_SCHEMA);
    schemaReady = true;
  };

  const exclusive = async <T>(fn: () => T): Promise<T> => {
    if (session().holding && txOpen) return fn();
    await mutex.lock();
    try {
      return fn();
    } finally {
      mutex.unlock();
    }
  };

  return {
    prepare(sql: string): Statement {
      return {
        get(...params: unknown[]) {
          return exclusive(() => {
            ensure();
            return database.prepare(sql).get(...params);
          });
        },
        all(...params: unknown[]) {
          return exclusive(() => {
            ensure();
            const rows = database.prepare(sql).all(...params);
            return rows;
          });
        },
        run(...params: unknown[]) {
          return exclusive(() => {
            ensure();
            return database.prepare(sql).run(...params);
          });
        },
      };
    },
    async exec(sql: string) {
      const command = sql.trim().toUpperCase();
      if (command === "BEGIN") {
        const state = session();
        if (state.holding) throw new Error("A database transaction is already open.");
        state.holding = true;
        let locked = false;
        try {
          await mutex.lock();
          locked = true;
          if (txOpen) throw new Error("A database transaction is already open.");
          ensure();
          database.exec("BEGIN");
          txOpen = true;
        } catch (error) {
          state.holding = false;
          if (locked) mutex.unlock();
          throw error;
        }
        return;
      }
      if (command === "COMMIT" || command === "ROLLBACK") {
        const state = session();
        if (!txOpen || !state.holding) {
          state.holding = false;
          return;
        }
        try {
          database.exec(command);
        } catch (error) {
          if (command !== "ROLLBACK") {
            try {
              database.exec("ROLLBACK");
            } catch {
              // The original statement error is the one to surface.
            }
          }
          throw error;
        } finally {
          txOpen = false;
          state.holding = false;
          mutex.unlock();
        }
        return;
      }
      await exclusive(() => {
        ensure();
        database.exec(sql);
      });
    },
  };
}

function bind(params: unknown[]): Array<string | number | boolean | null> {
  return params.map((value) => {
    if (value === undefined || value === null) return null;
    if (typeof value === "string" || typeof value === "number" || typeof value === "boolean") return value;
    if (typeof value === "bigint") return Number(value);
    throw new Error("Unsupported database parameter.");
  });
}

function toPostgresPlaceholders(sql: string): string {
  let index = 0;
  let out = "";
  let i = 0;
  while (i < sql.length) {
    const ch = sql[i];
    if (ch === "'") {
      const start = i;
      i += 1;
      while (i < sql.length) {
        if (sql[i] === "'") {
          if (sql[i + 1] === "'") {
            i += 2;
            continue;
          }
          i += 1;
          break;
        }
        i += 1;
      }
      out += sql.slice(start, i);
      continue;
    }
    if (ch === "-" && sql[i + 1] === "-") {
      const start = i;
      i += 2;
      while (i < sql.length && sql[i] !== "\n") i += 1;
      out += sql.slice(start, i);
      continue;
    }
    if (ch === "?") {
      index += 1;
      out += `$${index}`;
      i += 1;
      continue;
    }
    out += ch;
    i += 1;
  }
  return out;
}

function createPostgres(url: string): Db {
  let sql: QueryClient;
  try {
    sql = postgres(url, {
      max: 1,
      idle_timeout: 20,
      connect_timeout: 10,
      prepare: false,
      fetch_types: false,
      types: {
        int8: {
          to: 20,
          from: [20],
          serialize: (value: number | string) => String(value),
          parse: (value: string) => Number(value),
        },
      },
    }) as unknown as QueryClient;
  } catch {
    throw new Error("Could not open the database. Check DATABASE_URL.");
  }

  let schema: Promise<void> | null = null;
  const ensure = () => {
    if (!schema) {
      schema = (async () => {
        for (const statement of POSTGRES_SCHEMA) {
          await sql.unsafe(statement);
        }
      })().catch((error: unknown) => {
        schema = null;
        throw error;
      });
    }
    return schema;
  };

  const query = async (text: string, params: unknown[]) => {
    const state = session();
    await ensure();
    const client = state.reserved ?? sql;
    return client.unsafe(toPostgresPlaceholders(text), bind(params));
  };

  return {
    prepare(text: string): Statement {
      return {
        async get(...params: unknown[]) {
          const rows = await query(text, params);
          return rows[0];
        },
        async all(...params: unknown[]) {
          const rows = await query(text, params);
          return rows;
        },
        async run(...params: unknown[]) {
          const rows = await query(text, params);
          return { changes: Number(rows.count ?? 0), lastInsertRowid: 0 };
        },
      };
    },
    async exec(text: string) {
      const command = text.trim().toUpperCase();
      const state = session();
      if (command === "BEGIN") {
        if (state.reserved) throw new Error("A database transaction is already open.");
        await ensure();
        const reserved = await sql.reserve();
        try {
          await reserved.unsafe("BEGIN");
        } catch (error) {
          reserved.release();
          throw error;
        }
        state.reserved = reserved;
        return;
      }
      if (command === "COMMIT" || command === "ROLLBACK") {
        const reserved = state.reserved;
        if (!reserved) return;
        state.reserved = null;
        try {
          await reserved.unsafe(command);
        } catch (error) {
          if (command !== "ROLLBACK") {
            try {
              await reserved.unsafe("ROLLBACK");
            } catch {
              // The original statement error is the one to surface.
            }
          }
          throw error;
        } finally {
          reserved.release();
        }
        return;
      }
      await ensure();
      await sql.unsafe(text);
    },
  };
}

const globalForDb = globalThis as unknown as { __dramameDb?: Db; __dramameDbMode?: "postgres" | "sqlite" };

export function getDb(): Db {
  const mode = process.env.DATABASE_URL?.trim() ? "postgres" : "sqlite";
  if (!globalForDb.__dramameDb || globalForDb.__dramameDbMode !== mode) {
    const url = process.env.DATABASE_URL?.trim();
    globalForDb.__dramameDb = url ? createPostgres(url) : createSqlite();
    globalForDb.__dramameDbMode = mode;
  }
  return globalForDb.__dramameDb;
}
